GetAccredited/Models/Accreditation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GetAccredited.Models
{
    /// <summary>
    /// An accreditation is a skill evaluation certification being offered by an organization.
    /// </summary>
    public class Accreditation
    {
        public int AccreditationId { get; set; }
        public Organization Organization { get; set; }
        public string Name { get; set; }
        public DateTime DateCreated { get; set; }
        public string CreatorId { get; set; }
        public string Type { get; set; }
        public string Eligibility { get; set; }
        public string EligibilityFileURL { get; set; }

        /// <summary>
        /// Returns a string representation of this accreditation.
        /// </summary>
        /// <returns>String representation of this accreditation instance</returns>
        public override string ToString() => Name;

        /// <summary>
        /// Returns a list of string that represent the types of accreditation being offered by the system.
        /// </summary>
        /// <returns>List of accreditation types</returns>
        public static List<string> GetTypes()
        {
            return new List<string>
            {
                "Agriculture, Food and Natural Resources",
                "Architecture and Construction",
                "Arts, Audio/Video Technology and Communications",
                "Business Management and Administration",
                "Education and Training",
                "Finance",
                "Government and Public Administration",
                "Health Science",
                "Hospitality and Tourism",
                "Human Services",
                "Information Technology",
                "Law, Public Safety, Corrections and Security",
                "Manufacturing",
                "Marketing, Sales and Service",
                "Science, Technology, Engineering and Mathematics",
                "Transportation, Distribution and Logistics"
            };
        }
    }
}

GetAccredited/Models/ViewModels/AccreditationViewModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GetAccredited.Models.ViewModels
{
    public class AccreditationViewModel
    {
        public Accreditation Accreditation { get; set; }
        public IFormFile Eligibility { get; set; }
    }
}

GetAccredited/Controllers/AccreditationController.cs
using GetAccredited.Models;
using GetAccredited.Models.Repositories;
using GetAccredited.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace GetAccredited.Controllers
{
    /// <summary>
    /// The controller class for accreditation-related actions.
    /// </summary>
    [Authorize]
    public class AccreditationController : Controller
    {
        private UserManager<ApplicationUser> userManager;
        private IAppointmentRepository appointmentRepository;
        private IOrganizationRepository organizationRepository;
        private IAccreditationRepository accreditationRepository;
        private IWebHostEnvironment env;

        public AccreditationController(UserManager<ApplicationUser> userMgr,
            IOrganizationRepository organizationRepo, IAccreditationRepository accreditationRepo,
            IAppointmentRepository appointmentRepo, IWebHostEnvironment _env)
        {
            userManager = userMgr;
            organizationRepository = organizationRepo;
            accreditationRepository = accreditationRepo;
            appointmentRepository = appointmentRepo;
            env = _env;
        }

        [Authorize(Roles = Utility.ROLE_STUDENT)]
        public ViewResult BrowseAccreditations(string SearchKey, string SearchBy, string AccreditationType)
        {
            var accreditations = accreditationRepository.Accreditations;

            if (SearchKey != null)
            {
                if (SearchBy == "Organization")
                {
                    accreditations = accreditations.Where(a => a.Organization.Name.ToLower().Contains(SearchKey.Trim().ToLower()));
                }
                else
                {
                    accreditations = accreditations.Where(a => a.Name.ToLower().Contains(SearchKey.Trim().ToLower()));
                }
            }

            if (AccreditationType != null)
            {
                accreditations = accreditations.Where(a => a.Type == AccreditationType);
            }

            return View("Browse", new BrowseAccreditationsViewModel
            {
                Accreditations = accreditations.OrderBy(a => a.Organization.Name)
                .ThenBy(a => a.Name),
                SearchKey = SearchKey,
                SearchBy = SearchBy,
                AccreditationType = AccreditationType
            });
        }

        [HttpGet]
        [Authorize(Roles = Utility.ROLE_REP)]
        public ViewResult Create()
        {
            return View("CreateAccreditation", new AccreditationViewModel()
            {
                Accreditation = new Accreditation()
            });
        }

        [Authorize(Roles = Utility.ROLE_REP)]
        public async Task<ViewResult> Delete(int accreditationId)
        {
            var representative = await userManager.GetUserAsync(User);
            ViewResult result = View("AccreditationList", accreditationRepository.Accreditations
                    .Where(a => a.Organization.OrganizationId == representative.OrganizationId));

            // check if Accreditation exists
            var accreditation = accreditationRepository.Accreditations.FirstOrDefault(a => a.AccreditationId == accreditationId);
            if (accreditation == null)
            {
                TempData["message"] = "Failed to delete accreditation because it does not exist.";
                return result;
            }

            // check if current user is authorized to delete Accreditation
            if (representative.OrganizationId != accreditation.Organization.OrganizationId)
            {
                TempData["message"] = "You do not have enough rights to delete this accreditation as it does not belong to your organization.";
                return result;
            }

            // check if Accreditation is booked
            // retrieve all appointments
            var bookings = appointmentRepository.Bookings.Where(b => b.Accreditation == accreditation);

            // check if there are scheduled appointments with this accreditation, don't allow deletion if there's any
            if (bookings.ToList().Any(b => !b.Appointment.IsPast && b.Appointment.IsBooked))
            {
                TempData["message"] = $"{accreditation.Name} was not deleted. An appointment is currently booked with this accreditation.";
                return result;
            }

            // delete Accreditation
            var deletedAccreditation = accreditationRepository.DeleteAccreditation(accreditationId);
            if (deletedAccreditation != null)
                TempData["message"] = "Accreditation successfully deleted.";
            else
                TempData["message"] = "Failed to delete accreditation due to some unknown error.";

            // return to Accreditation List
            return result;
        }

        [Authorize(Roles = Utility.ROLE_REP)]
        public IActionResult DeleteRequirementsFile(int accreditationId)
        {
            var accreditation = accreditationRepository.Accreditations
                .FirstOrDefault(a => a.AccreditationId == accreditationId);

            if (accreditation == null) // if accreditation does not exist, return to home
            {
                TempData["message"] = "This accreditation does not exist.";
                return RedirectToAction("Index", "Home");
            }

            // delete file if there is an existing one
            if (Utility.DeleteFile(env.WebRootPath + Utility.REQUIREMENTS_DIR + accreditation.EligibilityFileURL))
            {
                // clear EligibilityFileURL property
                accreditation.EligibilityFileURL = null;

                // save changes
                accreditationRepository.SaveAccreditation(accreditation);

                TempData["message"] = "Requirements document has been successfully deleted.";
            }
            else // there is no file
            {
                TempData["message"] = "There is no requirements document associated with this accreditation.";
            }

            // return to edit view
            return View("CreateAccreditation", new AccreditationViewModel()
            {
                Accreditation = accreditation
            });
        }

        [HttpGet]
        [Authorize(Roles = Utility.ROLE_REP)]
        public ViewResult Edit(int accreditationId)
        {
            var res = View("CreateAccreditation", new AccreditationViewModel()
            {
                Accreditation = accreditationRepository.Accreditations
                .FirstOrDefault(a => a.AccreditationId == accreditationId)
            });
            return res;
        }

        [Authorize(Roles = Utility.ROLE_STUDENT)]
        public ViewResult Eligibility(int accreditationId)
        {
            return View("Eligibility", accreditationRepository.Accreditations
                .Where(a => a.AccreditationId == accreditationId)
                .First());
        }

        [Authorize(Roles = Utility.ROLE_REP)]
        public async Task<ViewResult> List()
        {
            var representative = await userManager.GetUserAsync(User);

            return View("AccreditationList", accreditationRepository.Accreditations
                .Where(a => a.Organization.OrganizationId == representative.OrganizationId));
        }

        [HttpPost]
        [Authorize(Roles = Utility.ROLE_REP)]
        public async Task<IActionResult> Save(AccreditationViewModel model)
        {
            if (ModelState.IsValid)
            {
                // accreditation is being created
                if (model.Accreditation.AccreditationId == 0)
                {
                    var creator = await userManager.GetUserAsync(User);
                    model.Accreditation.CreatorId = creator.Id;
                    model.Accreditation.Organization = organizationRepository.Organizations
                        .FirstOrDefault(o => o.OrganizationId == creator.OrganizationId);
                    model.Accreditation.DateCreated = DateTime.Now;
                    TempData["message"] = "Accreditation successfully created.";
                }

                // accreditation is being updated
                else
                {
                    TempData["message"] = "Accreditation successfully updated.";
                }

                // check if a file is uploaded
                if (model.Eligibility != null)
                {
                    // if there is an existing file, delete it
                    Utility.DeleteFile(env.WebRootPath + Utility.REQUIREMENTS_DIR + model.Accreditation.EligibilityFileURL);

                    // upload new file
                    model.Accreditation.EligibilityFileURL = await Utility.UploadFile(model.Eligibility, env.WebRootPath + Utility.REQUIREMENTS_DIR);
                    model.Accreditation.Eligibility = "N/A";
                }

                accreditationRepository.SaveAccreditation(model.Accreditation);
                return RedirectToAction("List");
            }

            return View("CreateAccreditation", model);
        }
    }
}

GetAccredited/Views/Accreditation/AccreditationList.cshtml
@model IEnumerable<Accreditation>
@{ ViewBag.Title = "Accreditations"; }

<div class="row">
    <h2>
        Accreditation List
    </h2>
</div>

<div class="row">
    <table class="repaccredlist">
        <thead>
            <tr class="repaccredlist_tr">
                <th class="repaccredlist_th">Name</th>
                <th class="repaccredlist_th">Type</th>
                <th class="repaccredlist_th">Date Created</th>
                <th class="repaccredlist_th">Created by</th>
                <th class="repaccredlist_th">Actions</th>
            </tr>
        </thead>

        <tbody>
            @if (Model != null)
            {
                @foreach (var accreditation in Model)
                {
                    <tr class="repaccredlist_tr">
                        <td class="repaccredlist_td">@accreditation</td>
                        <td class="repaccredlist_td">@accreditation.Type</td>
                        <td class="repaccredlist_td">@accreditation.DateCreated.ToString("M/dd/yyyy")</td>
                        <td class="repaccredlist_td">@(accreditation.CreatorId == null ? "user removed": (await userManager.FindByIdAsync(accreditation.CreatorId)).ToString())</td>
                        <td class="repaccredlist_td">
                            <a class="repaccredlist_crud" asp-controller="Accreditation"
                               asp-action="Edit"
                               asp-route-accreditationId="@accreditation.AccreditationId">Edit</a> | <a class="repaccredlist_crud"  href="javascript:deleteAccreditation('@accreditation.AccreditationId');">Delete</a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>

    <div class="row">
        <a class="btn_accredlist" asp-controller="Accreditation"
           asp-action="Create">Create an Accreditation</a>
    </div>
</div>

GetAccredited/Views/Accreditation/Browse.cshtml
@model BrowseAccreditationsViewModel
@{
    ViewBag.Title = "Browse Accreditations";
}

<div class="row">
    <h2>
        Browse Accreditations
    </h2>
</div>

<div class="row browseaccred-container">
    <form asp-controller="Accreditation" asp-action="BrowseAccreditations">
        <table>
            <tr>
                <td>Search by:</td>
                <td><input asp-for="SearchKey" placeholder="Search" /></td>
            </tr>

            <tr>
                <td>&nbsp;</td>
                <td>
                    <select asp-for="SearchBy" required>
                        <option value="">Select a category...</option>
                        <option>Accreditation</option>
                        <option>Organization</option>
                    </select>
                </td>
            </tr>

            <tr>
                <td>Accreditation Type:</td>
                <td>
                    <select asp-for="AccreditationType">
                        <option value="">Any</option>
                        @foreach (var type in Accreditation.GetTypes())
                        {
                            <option value="@type">@type</option>
                        }
                    </select>
                </td>
            </tr>

            <tr>
                <td><input type="submit" value="Search" /></td>
            </tr>
        </table>
    </form>
</div>

<div class="row">
    <h1>
        &nbsp;
    </h1>
</div>

<div class="row">
    <table class="accredlist">
        <thead>
            <tr class="accredlist_tr">
                <th class="accredlist_th">Accreditation</th>
                <th class="accredlist_th">Organization</th>
                <th class="accredlist_th">Type</th>
                <th class="accredlist_th">Actions</th>
            </tr>
        </thead>

        <tbody>
            @foreach (var accreditation in Model.Accreditations)
            {
                <tr class="accredlist_tr">
                    <td class="accredlist_td">@accreditation</td>
                    <td class="accredlist_td">@accreditation.Organization.Name</td>
                    <td class="accredlist_td">@accreditation.Type</td>
                    <td class="accredlist_td">
                        <a class="accredlist_crud" asp-controller="Appointment"
                           asp-action="BookAppointment"
                           asp-route-accreditationId="@accreditation.AccreditationId">Book an Appointment</a> |
                        <a class="accredlist_crud" asp-controller="Accreditation"
                           asp-action="Eligibility"
                           asp-route-accreditationId="@accreditation.AccreditationId">Check Eligibility</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

GetAccredited/Views/Accreditation/CreateAccreditation.cshtml
@model AccreditationViewModel
@{
    bool isCreate = Model.Accreditation.AccreditationId == 0;
    ViewBag.Title = isCreate ? "Create an Accreditation" : "Edit Accreditation";
}

<div class="row">
    <h2>
        @(isCreate ? "Create an Accreditation" : "Edit Accreditation")
    </h2>
</div>

<div class="row accred-container">
    <form asp-controller="Accreditation" asp-action="Save" method="post" enctype="multipart/form-data">
        <input asp-for="Accreditation.AccreditationId" type="hidden" />

        <table>
            <tr>
                <td><h3>Accreditation Details</h3></td>
            </tr>
            <tr>
                <td>Name:</td>
                <td>
                    <input asp-for="Accreditation.Name" type="text" required />

                    <!-- Hidden Inputs -->
                    <input asp-for="Accreditation.CreatorId" hidden />
                    <input asp-for="Accreditation.EligibilityFileURL" hidden />
                </td>
            </tr>
            <tr>
                <td>Type:</td>
                <td>
                    <select asp-for="Accreditation.Type" required>
                        <option value="">Select type</option>
                        @foreach (var accreditation in Accreditation.GetTypes())
                        {
                            <option value="@accreditation">@accreditation</option>
                        }
                    </select>
                </td>
            </tr>
            <!-- Eligibility Requirements -->
            <tr>
                <td><h3>Eligibility Requirements</h3></td>
            </tr>

            <!-- Manual Insertion -->
            @if (Model.Accreditation.EligibilityFileURL == null)
            {
                <tr>
                    <td class="accred_elig_label">Type in requirements:</td>
                    <td><textarea class="accred_elig" asp-for="Accreditation.Eligibility" required></textarea></td>
                </tr>
            }

            <!-- Upload PDF -->
            <tr>
                <td class="accred_elig_label"><i>@(Model.Accreditation.EligibilityFileURL == null ? "OR " : "")</i>Upload a PDF File:</td>
                <td>
                    <input asp-for="Eligibility" type="file" accept="application/pdf"
                           onchange="validateExtension(this, 'doc'); eligibilityFileSelected(true);" />
                    <button type="button" class="btn_accred_remove" onclick="removeFileSelected(this)" hidden>Remove</button>

                    @if (Model.Accreditation.EligibilityFileURL != null)
                    {
                        <br /> <br />
                        <span class="warning_accred_delete">Warning: Uploading a new eligibility requirements</span><br />
                        <span class="warning_accred_delete">document for this accreditation will overwrite</span><br />
                        <span class="warning_accred_delete">the <a href="~/data/requirements/@Model.Accreditation.EligibilityFileURL" target="_blank" title="View in a new tab">current document</a> saved in the system.</span>

                        <!-- Delete -->
                        <br /> <br />
                        <button type="button" class="btn_accred_delete" onclick="deleteAccreditationFile(@Model.Accreditation.AccreditationId);">Delete File from the System</button>
                    }
                </td>
            </tr>

            <!-- Submit -->
            <tr>
                <td><input type="submit" value=@(isCreate ? "Create" : "Save") /></td>
            </tr>
        </table>
    </form>
</div>

GetAccredited/Views/Accreditation/Eligibility.cshtml
@model Accreditation
@{ ViewBag.Title = Model.Name; }

<div class="row">
    <h2>
        @Model
    </h2>
</div>

<div>
    <center>
        @if (Model.Organization.Logo != null)
        {
            <img src="~/images/logos/@Model.Organization.Logo" height="100" />
        }
    </center>
</div>

<div class="row">
    <div class="col span-1-of-1">
        <div class="eligibility_box">
            @if (Model.EligibilityFileURL == null)
            {
                <h1 class="eligibility_title">
                    @Model.Organization
                </h1><br />
                <p>If you want to be considered for this accreditation, you must meet the following eligibility requirements before applying:</p> <br />
                <pre>@Model.Eligibility</pre>
            }
            else
            {
                <embed class="pdf" src="~/data/requirements/@Model.EligibilityFileURL" type="application/pdf" />
            }


        </div>
    </div>
</div>