GetAccredited/Controllers/AppointmentController.cs
using GetAccredited.Models;
using GetAccredited.Models.Repositories;
using GetAccredited.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GetAccredited.Controllers
{
    /// <summary>
    /// The controller class for appointment-related actions.
    /// </summary>
    [Authorize]
    public class AppointmentController : Controller
    {
        private UserManager<ApplicationUser> userManager;
        private IAccreditationRepository accreditationRepository;
        private IAppointmentRepository appointmentRepository;
        private IOrganizationRepository organizationRepository;

        public AppointmentController(UserManager<ApplicationUser> userMgr,
            IAppointmentRepository repo, IOrganizationRepository organizationRepo, IAccreditationRepository accreditationRepo)
        {
            userManager = userMgr;
            accreditationRepository = accreditationRepo;
            appointmentRepository = repo;
            organizationRepository = organizationRepo;
        }

        [Authorize(Roles = Utility.ROLE_REP)]
        public async Task<IActionResult> ApproveRequest(int requestId)
        {
            var request = appointmentRepository.Requests.FirstOrDefault(r => r.RequestId == requestId);
            if (request == null)
            {
                TempData["message"] = "Request not found.";
                return await Requests();
            }

            // if reschedule, set Booking.Appointment.StudentId to null and Booking.Appointment to NewAppointment
            if (request.IsCancel)
            {
                appointmentRepository.DeleteRequest(request);
                await CancelAppointment(request.Booking.Appointment.AppointmentId);
            }
            else
            {
                var oldAppointment = request.Booking.Appointment;
                if (request.NewAppointment.IsBooked)
                {
                    TempData["message"] = "The requested time slot is already booked by another student.";
                    appointmentRepository.DeleteRequest(request);
                    return await Requests();
                }
                request.NewAppointment.StudentId = oldAppointment.StudentId;
                request.Booking.Appointment = request.NewAppointment;
                oldAppointment.StudentId = null;

                appointmentRepository.SaveAppointment(oldAppointment);
                appointmentRepository.SaveAppointment(request.NewAppointment);
                appointmentRepository.SaveBooking(request.Booking);
                appointmentRepository.DeleteRequest(request);
            }

            TempData["message"] = "Request approved.";
            return await Requests();
        }

        [HttpGet]
        [Authorize(Roles = Utility.ROLE_STUDENT)]
        public IActionResult BookAppointment(string organizationId, int accreditationId = 0)
        {
            var accreditation = accreditationId > 0 ? accreditationRepository.Accreditations.First(a => a.AccreditationId == accreditationId) :
                null;
            var organization = accreditation == null ? organizationRepository.Organizations.First(o => o.OrganizationId == organizationId) :
                accreditation.Organization;
            var accreditations = accreditationRepository.Accreditations.Where(a => a.Organization == organization);
            var appointments = appointmentRepository.Appointments.ToList()
                .Where(a => a.Organization == organization)
                .Where(a => !a.IsBooked && !a.IsPast)
                .OrderBy(a => a.Date).ThenBy(a => a.Start);
            if (!appointments.Any())
            {
                TempData["message"] = "This organization currently has no time slots available.";
                return RedirectToAction("BrowseAccreditations", "Accreditation");
            }
            return View(new BookAppointmentViewModel
            {
                Organization = organization,
                Accreditations = accreditations,
                Appointments = appointments,
                AccreditationId = accreditationId
            });
        }

        [HttpPost]
        [Authorize(Roles = Utility.ROLE_STUDENT)]
        public async Task<IActionResult> BookAppointment(BookAppointmentViewModel model)
        {
            if (ModelState.IsValid)
            {
                var student = await userManager.GetUserAsync(User);
                var accreditation = accreditationRepository.Accreditations.First(a => a.AccreditationId == model.AccreditationId);
                var appointment = appointmentRepository.Appointments.First(a => a.AppointmentId == model.AppointmentId);
                var card = appointmentRepository.Cards.FirstOrDefault(c => c.CustomerId == student.Id);
                return View("Payment", new PaymentViewModel
                {
                    Accreditation = accreditation,
                    Appointment = appointment,
                    Card = card
                });
            }

            return View(model);
        }

        [Authorize(Roles = Utility.ROLE_REP)]
        public async Task<IActionResult> CancelAppointment(int appointmentId)
        {
            var appointment = appointmentRepository.Appointments.FirstOrDefault(a => a.AppointmentId == appointmentId);
            if (appointment == null)
            {
                TempData["message"] = "Failed to cancel appointment because it does not exist.";
                return await List();
            }

            var booking = appointmentRepository.Bookings
                .FirstOrDefault(b => b.Appointment.AppointmentId == appointmentId &&
                b.StudentId == appointment.StudentId);

            if (booking == null)
            {
                TempData["message"] = "This appointment is not booked.";
                return await List();
            }

            // update appointment and booking entries
            appointment.StudentId = null;
            booking.IsCancelled = true;
            appointmentRepository.SaveBooking(booking);
            appointmentRepository.SaveAppointment(appointment);
            TempData["message"] = "The appointment has been successfully cancelled.";
            return await List();
        }

        [HttpPost]
        [Authorize(Roles = Utility.ROLE_STUDENT)]
        public async Task<IActionResult> CompleteBooking(PaymentViewModel model)
        {
            var accreditation = accreditationRepository.Accreditations.First(a => a.AccreditationId == model.Accreditation.AccreditationId);
            var appointment = appointmentRepository.Appointments.First(a => a.AppointmentId == model.Appointment.AppointmentId);

            // check if appointment has already been booked
            if (appointment.IsBooked)
            {
                ModelState.AddModelError("", "Failed to book appointment. The appointment has already been booked.");
                return RedirectToAction("Index", "Home");
            }

            // check if card is expired
            if (model.Card.IsExpired)
                ModelState.AddModelError("", "Payment rejected. The card has expired.");

            if (ModelState.IsValid)
            {
                var student = await userManager.GetUserAsync(User);
                appointment.StudentId = student.Id;

                // save appointment and record booking
                appointmentRepository.SaveAppointment(appointment);
                appointmentRepository.SaveBooking(new Booking
                {
                    StudentId = student.Id,
                    Appointment = appointment,
                    Accreditation = accreditation,
                    DateBooked = DateTime.Now
                });

                // if user wants to save their card info, save to db
                if (model.SaveInfo)
                {
                    model.Card.CustomerId = student.Id;
                    appointmentRepository.SaveCard(model.Card);
                }

                TempData["message"] =
                    $"Payment accepted. Thank you. " +
                    $"You have successfully booked an appointment with {accreditation.Organization.Name} " +
                    $"on {appointment.Date:MMMM d, yyyy}, from {appointment.Start:h:mm tt} to {appointment.End:h:mm tt}.";
                return RedirectToAction("Index", "Home");
            }

            return View("Payment", new PaymentViewModel
            {
                Accreditation = accreditation,
                Appointment = appointment,
                Card = model.Card,
                SaveInfo = model.SaveInfo
            });
        }

        [HttpGet]
        [Authorize(Roles = Utility.ROLE_REP)]
        public ViewResult Create()
        {
            return View("CreateAppointment", new Appointment() { Date = DateTime.Now });
        }

        [HttpGet]
        [Authorize(Roles = Utility.ROLE_REP)]
        public ViewResult CreateMultiple()
        {
            return View(new AppointmentsViewModel() { Date = DateTime.Now });
        }

        [HttpPost]
        [Authorize(Roles = Utility.ROLE_REP)]
        public async Task<IActionResult> CreateMultiple(AppointmentsViewModel model)
        {
            // check if date is NOT in the past
            if (model.Date < DateTime.Today ||
                (model.Date == DateTime.Today && model.Start < DateTime.Now))
            {
                ModelState.AddModelError("", "Please select a start time and date in the future.");
            }

            // retrieve current representative user and their organization
            var representative = await userManager.GetUserAsync(User);
            var organization = organizationRepository.Organizations

GetAccredited/Views/Shared/_Layout.cshtml
@inject Microsoft.Extensions.Configuration.IConfiguration configuration
@{
    var appTitle = configuration["Title"];
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Get Accredited Appointment Booking Application">

    <script src="~/js/scripts.js" asp-append-version="true"></script>
    <link rel="stylesheet" type="text/css" href="~/css/styles.css" asp-append-version="true">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" asp-append-version="true" />
    <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;1,300&display=swap" rel="stylesheet" asp-append-version="true">
    <link rel="icon" href="~/images/icon.png" />
    <title>@ViewBag.Title | @appTitle</title>
</head>

<body>
    <!-- Navigation Here -->
    <header>
        <nav>
            <div class="navbar">
                <a asp-controller="Home" asp-action="Index" class="logo">
                    <strong title="Home"><span class="logo-accent">get</span>Accredited</strong>
                </a>
                <ul class="main-nav">
                    <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                    @if (User.IsStudent())
                    {
                        <li><a asp-controller="Account" asp-action="Profile">Profile</a></li>
                        <li><a asp-controller="Appointment" asp-action="MyAppointments">Appointments</a></li>
                        <li><a asp-controller="Accreditation" asp-action="BrowseAccreditations">Accreditations</a></li>
                        <li><a asp-controller="Organization" asp-action="List">Organizations</a></li>
                    }
                    @if (User.IsRepresentative())
                    {
                        <li>
                            <a asp-controller="Organization"
                               asp-action="Display"
                               asp-route-organizationId="@((await userManager.GetUserAsync(User)).OrganizationId)">My Organization</a>
                        </li>
                        <li><a asp-controller="Appointment" asp-action="List">Appointments</a></li>
                        <li><a asp-controller="Accreditation" asp-action="List">Accreditations</a></li>
                    }
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a asp-controller="Account" asp-action="Logout">Logout</a></li>
                    }
                </ul>
            </div>
        </nav>
    </header>

    <!-- Body -->
    <section>
        <!-- Message -->
        @if (TempData["message"] != null)
        {
            <div class="row message">
                <ul><li>@TempData["message"]</li></ul>
            </div>
        }

        <!-- Errors -->
        <div class="row validation">
            <div asp-validation-summary="All"></div>
        </div>

        @RenderBody()
    </section>

    <!-- Footer -->
    <div class="footer">
        <p>© Group 2 | COMP 313 SEC 001 W21</p>
    </div>
</body>
</html>