GetAccredited/Models/Organization.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GetAccredited.Models
{
    /// <summary>
    /// An organization offers accreditations to students and other job-seekers.
    /// </summary>
    public class Organization
    {
        public String OrganizationId { get; set; }
        public String Name { get; set; }
        public String Acronym { get; set; }
        public String Description { get; set; }
        public String Logo { get; set; }
        public String WebsiteUrl { get; set; }

        /// <summary>
        /// Returns a string representation of this organization.
        /// </summary>
        /// <returns>A string that represents this organization instance</returns>
        public override String ToString() => $"{Name} ({Acronym})";
    }
}

GetAccredited/Models/ViewModels/UploadLogoViewModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GetAccredited.Models.ViewModels
{
    public class UploadLogoViewModel
    {
        public Organization Organization { get; set; }
        public IFormFile Logo { get; set; }
    }
}

GetAccredited/Controllers/OrganizationController.cs
using GetAccredited.Models;
using GetAccredited.Models.Repositories;
using GetAccredited.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Threading.Tasks;

namespace GetAccredited.Controllers
{
    /// <summary>
    /// The controller class for organization-related actions.
    /// </summary>
    [Authorize]
    public class OrganizationController : Controller
    {
        private readonly IOrganizationRepository organizationRepository;
        private IAccreditationRepository accreditationRepository;
        private IAppointmentRepository appointmentRepository;
        private readonly UserManager<ApplicationUser> userManager;
        private IWebHostEnvironment env;

        public OrganizationController(IOrganizationRepository organizationRepo,
            IAccreditationRepository accreditationRepo,
            IAppointmentRepository appointmentRepo,
            UserManager<ApplicationUser> userMgr,
             IWebHostEnvironment _env)
        {
            organizationRepository = organizationRepo;
            accreditationRepository = accreditationRepo;
            appointmentRepository = appointmentRepo;
            userManager = userMgr;
            env = _env;
        }

        [HttpGet]
        [Authorize(Roles = Utility.ROLE_ADMIN)]
        public ViewResult Create()
        {
            return View("CreateOrganization", new Organization());
        }

        [HttpGet]
        [Authorize(Roles = Utility.ROLE_ADMIN)]
        public async Task<IActionResult> Delete(string organizationId)
        {
            // check if organization exists
            var organization = organizationRepository.Organizations.FirstOrDefault(o => o.OrganizationId == organizationId);
            if (organization == null)
            {
                TempData["message"] = "No organization deleted. This organization does not exist.";
                var res = List();
                res.StatusCode = StatusCodes.Status422UnprocessableEntity;
                return res;
            }

            // retrieve all appointments
            var appointments = appointmentRepository.Appointments.Where(a => a.Organization == organization);

            // check if there are scheduled appointments, don't allow deletion if there's any
            if (appointments.ToList().Any(a => !a.IsPast && a.IsBooked))
            {
                TempData["message"] = $"{organization.Name} was not deleted. The organization currently has at least one scheduled appointment at the moment.";
                return List();
            }

            // delete appointments
            appointmentRepository.DeleteAppointmentsByOrganization(organization);

            // delete accreditations
            accreditationRepository.DeleteAccreditationsByOrganization(organization);

            // delete representatives of this organization
            var reps = await userManager.GetRepresentativesByOrganization(organizationId);
            foreach (var r in reps)
            {
                var result = await userManager.DeleteAsync(r);
                if (!result.Succeeded)
                {
                    TempData["message"] = "Cannot delete a representative. Organization was not successfully deleted.";
                    return List();
                }
            }

            // delete the organization itself
            organizationRepository.DeleteOrganization(organization.OrganizationId);

            TempData["message"] = $"{organization.Name} has been successfully deleted.";
            return List();
        }

        public ViewResult Display(string organizationId)
        {
            ViewBag.Accreditations = accreditationRepository.Accreditations
                .Where(acc => acc.Organization.OrganizationId == organizationId);
            return View("OrganizationDetails", organizationRepository.Organizations
                .FirstOrDefault(o => o.OrganizationId == organizationId));
        }

        [HttpGet]
        [Authorize(Roles = Utility.ROLE_REP)]
        public async Task<IActionResult> Edit(string organizationId)
        {
            var rep = await userManager.GetUserAsync(User);
            if (rep.OrganizationId != organizationId)
            {
                TempData["message"] = "You do not have permission to edit this organization.";
                return RedirectToAction("Index", "Home");
            }
            return View("CreateOrganization", organizationRepository
                .Organizations.First(o => o.OrganizationId == organizationId));
        }

        [HttpPost]
        [Authorize(Roles = Utility.ROLE_ADMIN)]
        public async Task<IActionResult> Invite(RepresentativesViewModel model)
        {
            if (ModelState.IsValid)
            {
                model.Organization = organizationRepository.Organizations.
                    First(o => o.OrganizationId == model.Organization.OrganizationId);
                var inviteLink = $"{HttpContext.Request.Host}/Account/Register?role=representative";
                if (await Utility.SendInviteEmail(model.Email, model.Organization, inviteLink))
                {
                    TempData["message"] = $"Email sent to {model.Email}.";
                }
                else
                {
                    TempData["message"] = $"Something went wrong. No invitation email has been sent.";
                }
                return RedirectToAction("Representatives", new
                {
                    organizationId = model.Organization.OrganizationId
                });
            }
            return View("RepresentativeList", model);
        }

        [HttpGet]
        [Authorize(Roles = Utility.ROLE_ADMIN + "," + Utility.ROLE_STUDENT)]
        public ViewResult List()
        {
            return View("OrganizationList", organizationRepository.Organizations.OrderBy(o => o.Name));
        }

        [HttpGet]
        [Authorize(Roles = Utility.ROLE_ADMIN)]
        public async Task<IActionResult> RemoveRepresentative(String email)
        {
            // retrieve rep via email
            var rep = await userManager.FindByEmailAsync(email);

            // if email is invalid
            if (rep == null)
            {
                // set appropriate message
                TempData["message"] = $"No representative removed. There does not exist a representative with the email {email}.";
                return UnprocessableEntity();
            }

            // retrieve organization of the rep
            var org = organizationRepository.Organizations.First(o => o.OrganizationId == rep.OrganizationId);

            // attempt to delete rep
            var result = await userManager.DeleteAsync(rep);
            if (result.Succeeded)
            {
                // update accreditations created by this rep
                var accreditations = accreditationRepository.Accreditations.Where(a => a.CreatorId == rep.Id);
                foreach (var acc in accreditations.ToList())
                {
                    acc.CreatorId = null;
                    accreditationRepository.SaveAccreditation(acc);
                }

                // set appropriate message
                TempData["message"] = $"{rep.FirstName} {rep.LastName} is no longer a representative for {org.Name}.";
            }
            else
            {
                // set appropriate message
                TempData["message"] = $"Failed to remove {rep.FirstName} {rep.LastName} as a representative of {org.Name}.";
            }

            // return to manage representative page
            return View("RepresentativeList", new RepresentativesViewModel
            {
                Organization = org,
                Representatives = await userManager.GetRepresentativesByOrganization(org.OrganizationId)
            });
        }

        [HttpGet]
        [Authorize(Roles = Utility.ROLE_ADMIN)]
        public async Task<ViewResult> Representatives(string organizationId)
        {
            Organization organization = organizationRepository.Organizations
                .First(o => o.OrganizationId == organizationId);

            return View("RepresentativeList", new RepresentativesViewModel
            {
                Organization = organization,
                Representatives = await userManager.GetRepresentativesByOrganization(organizationId)
            });
        }

        [HttpPost]
        [Authorize(Roles = Utility.ROLE_ADMIN + "," + Utility.ROLE_REP)]
        public async Task<IActionResult> Save(Organization model)
        {
            if (ModelState.IsValid)
            {
                // organization is being created
                if (model.OrganizationId == null)
                {
                    model.OrganizationId = Utility.GenerateId();
                    TempData["message"] = $"{model.Name} successfully created.";
                }

                // organization is being updated
                else
                {
                    string orgId = (await userManager.GetUserAsync(User)).OrganizationId;
                    TempData["message"] = $"{model.Name} successfully updated.";
                    organizationRepository.SaveOrganization(model);
                    return RedirectToAction("Display", new { organizationId = orgId });
                }

                organizationRepository.SaveOrganization(model);
                return RedirectToAction("Representatives", new { organizationId = model.OrganizationId });
            }
            return View("CreateOrganization", model);
        }

        [HttpGet]
        [Authorize(Roles = Utility.ROLE_REP)]
        public async Task<IActionResult> UploadLogo(string organizationId)
        {

GetAccredited/Views/Organization/CreateOrganization.cshtml
@model Organization
@{
    bool isCreate = Model.OrganizationId == null;
    ViewBag.Title = isCreate ? "Create an Organization" : "Edit Organization";
}

<div class="row">
    <h2>
        @(isCreate ? "Create an Organization" : "Edit Organization")
    </h2>
</div>

<div class="row org-container">
    <form asp-controller="Organization" asp-action="Save" method="post">
        <!-- Hidden input(s) -->
        <input asp-for="OrganizationId" type="hidden" />

        <table>
            <!-- Name -->
            <tr>
                <td>Name:</td>
                <td><input asp-for="Name" type="text" required /></td>
            </tr>

            <!-- Acronym -->
            <tr>
                <td>Acronym:</td>
                <td><input asp-for="Acronym" type="text" required /></td>
            </tr>

            <!-- Description -->
            <tr>
                <td class="org_description_label">Provide a description:</td>
                <td><textarea class="org_description" asp-for="Description" required></textarea></td>
            </tr>

            <!-- Website (Optional) -->
            <tr>
                <td>Website URL:</td>
                <td><input asp-for="WebsiteUrl" type="url" /></td>
            </tr>

            <!-- Submit button -->
            <tr>
                <td><input type="submit" value=@(isCreate?"Create":"Save") /></td>
            </tr>
        </table>
    </form>
</div>

GetAccredited/Views/Organization/OrganizationDetails.cshtml
@model Organization
@{
    ViewBag.Title = Model.Name;
    IEnumerable<Accreditation> accreditations = ViewBag.Accreditations;
}

<div class="row">
    <h2>
        Organization Details
    </h2>
</div>

<div>
    <center>
        @if (Model.Logo != null)
        {
            <img src="~/images/logos/@(Model.Logo)" height="100" />
        }
    </center>
</div>

<div class="row">
    <div class="col span-1-of-1">
        <!-- ORGANIZATION DETAILS -->
        <div class="org_details_box">
            <!-- Details -->
            <h1 class="org_details_title">
                @Model
            </h1><br>
            <p>@Model.Description</p><br>
            <p><a class="orgdetails_url" href="@Model.WebsiteUrl" target="_blank" title="Open website in a new tab">Go to website</a></p>
            @if (User.IsStudent())
            {
                <p>
                    <a class="orgdetails_url" asp-controller="Appointment"
                       asp-action="BookAppointment"
                       asp-route-organizationId="@Model.OrganizationId">Book an Appointment</a>
                </p>
            }
        </div>

        <div class="row">
            <br><br>
            <h2>
                Accreditations Offered
            </h2>
        </div>

        <!-- ACCREDITATIONS LIST -->
        <div class="row">
            <table class="accredlist">
                <thead>
                    <tr class="accredlist_tr">
                        <th class="accredlist_th">Name</th>
                        <th class="accredlist_th">Type</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var acc in accreditations)
                    {
                        <tr class="accredlist_tr">
                            <td class="accredlist_td">@acc.Name</td>
                            <td class="accredlist_td">@acc.Type</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>

        <!-- ACTIONS -->
        <div>
            @if (User.IsRepresentative())
            {
                <a class="org_details_btn" asp-controller="Organization"
                   asp-action="Edit"
                   asp-route-organizationId="@Model.OrganizationId">Edit Organization</a>
                <a class="org_details_btn" asp-controller="Organization"
                   asp-action="UploadLogo" asp-route-organizationId="@Model.OrganizationId"
                   title="Change or upload a new logo for the organization">Upload Logo</a>
            }
            @if (User.IsAdmin())
            {
                <br><br>
                <a class="org_details_btn" asp-controller="Organization"
                   asp-action="Representatives"
                   asp-route-organizationId="@Model.OrganizationId">Manage Representatives</a>
            }
        </div>
    </div>
</div>

GetAccredited/Views/Organization/OrganizationList.cshtml
@model IEnumerable<Organization>
@{ViewBag.Title = "Organizations"; }

<div class="row">
    <h2>
        Organization List
    </h2>
</div>

<div class="row">
    <table class="orglist">
        <thead>
            <tr class="orglist_tr">
                @if (User.IsAdmin())
                {
                    <th class="orglist_th">ID</th>
                }
                <th class="orglist_th">Name</th>
                <th class="orglist_th">Acronym</th>
                <th class="orglist_th">Website</th>
                <th class="orglist_th">Actions</th>
            </tr>

        </thead>
        <tbody>
            @foreach (Organization org in Model)
            {
                <tr class="orglist_tr">
                    @if (User.IsAdmin())
                    {
                        <td class="orglist_td">@org.OrganizationId</td>
                    }
                    <td class="orglist_td">@org.Name</td>
                    <td class="orglist_td">@org.Acronym</td>
                    <td class="orglist_td"><a class="orglist_url" href="@org.WebsiteUrl" target="_blank" title="Open website in a new tab">@org.WebsiteUrl</a></td>
                    <td class="orglist_td">
                        <a class="orglist_crud" asp-controller="Organization"
                           asp-action="Display"
                           asp-route-organizationId="@org.OrganizationId">View Details</a>
                        @if (User.IsAdmin())
                        {
                            <text>|</text>
                            <a class="orglist_crud" asp-controller="Organization"
                               asp-action="Representatives"
                               asp-route-organizationId="@org.OrganizationId">Manage Representatives</a>
                            <text>|</text>
                            <a class="orglist_crud" href="javascript:deleteOrganization('@org.OrganizationId')">Delete</a>
                        }
                        @if (User.IsStudent())
                        {
                            <text>|</text>
                            <a class="orglist_crud" asp-controller="Appointment" asp-action="BookAppointment"
                               asp-route-organizationId="@org.OrganizationId">Book Appointment</a>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
    @if (User.IsAdmin())
    {
        <div class="row">
            <a class="btn_orglist" asp-controller="Organization" asp-action="Create">Create an Organization</a>
        </div>
    }
</div>

GetAccredited/Views/Organization/RepresentativeList.cshtml
@model RepresentativesViewModel
@{ ViewBag.Title = "Manage Representatives"; }

<div class="row">
    <h2>
        Manage Representatives for @Model.Organization
    </h2>
</div>

<div class="row">
    @if (Model.Representatives.Any())
    {
        <table class="replist">
            <thead>
                <tr class="replist_tr">
                    <th class="replist_th">Name</th>
                    <th class="replist_th">Email Address</th>
                    <th class="replist_th">Action(s)</th>
                </tr>
            </thead>

            <tbody>
                @foreach (var rep in Model.Representatives)
                {
                    <tr class="replist_tr">
                        <td class="replist_td">@rep.ToString()</td>
                        <td class="replist_td">@rep.Email</td>
                        <td class="replist_td">
                            <a class="replist_crud" href="javascript:deleteRepresentative('@rep.Email');">Remove</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <center>This organization currently has no representatives.</center>
    }
</div>

<div class="row">
    <br><br>
    <h2>
        Invite a representative
    </h2>
</div>

<div class="row rep-container">
    <form asp-controller="Organization" asp-action="Invite" method="post">
        <input asp-for="Organization.OrganizationId" type="hidden" />
        <table>
            <!-- Email -->
            <tr>
                <td>Email:</td>
                <td><input asp-for="Email" type="email" required /></td>
            </tr>

            <!-- Verify email is correct -->
            <tr>
                <td colspan="2"><input type="checkbox" required /><span> I am certain that the email address provided is valid</span></td>
            </tr>

            <!-- Invite button -->
            <tr>
                <td> <input type="submit" value="Invite" /> </td>
            </tr>
        </table>

    </form>
</div>

GetAccredited/Views/Organization/UploadLogo.cshtml
@model UploadLogoViewModel
@{ ViewBag.Title = "Upload logo";}

<div class="row">
    <h2>
        Upload Organization Logo
    </h2>
</div>

<div class="row uploadfile-container">
    <form asp-controller="Organization" asp-action="UploadLogo" method="post" enctype="multipart/form-data">
        <!-- HIDDEN INPUTS -->
        <input type="hidden" asp-for="Organization.OrganizationId" />

        <table>
            <!-- Display organization LOGO if Exists -->
            @if (Model.Organization.Logo != null)
            {
                <tr>
                    <td>Current logo:<br />This will be overwritten if you upload a new logo.</td>
                    <td><img src="~/images/logos/@(Model.Organization.Logo)" height="100" /></td>
                </tr>
            }

            <!-- Image File -->
            <tr>
                <td>
                    Select image file (.jpeg, .jpg, or .png):
                </td>
                <td>
                    <input asp-for="Logo" type="file" accept=".jpeg, .jpg, .png" onchange="validateExtension(this, 'img')" required />
                </td>
            </tr>

            <!-- Upload File button -->
            <tr>
                <td>
                    <input type="submit" value="Upload Logo" />
                </td>
            </tr>
        </table>
    </form>
</div>